#!/bin/bash

# the L1 deposit number generated by deposit.sh
depositCount="$1"
if [[ -z "$depositCount" ]]
then
	echo "error: pass depositCount"
	exit 1
fi

args=(
	# L2 RPC node
	--rpc-url http://localhost:12345
	--insecure
	# default pre-funded dev account
	--private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
	--bridge-address 0x78908F7A87d589fdB46bdd5EfE7892C5aD6001b6
	# AggKit bridge service REST endpoint (see http://localhost:5579/bridge/v1/swagger )
    --bridge-service-url http://localhost:5579
    # L1 chain ID
	--deposit-network 0
	# L2 rollup chain ID
	--chain-id 1001
	--deposit-count $depositCount
	--legacy=false
	--dry-run
	# --verbosity trace
)

polycli ulxly claim asset "${args[@]}"
