#!/usr/bin/env bash
# Generate the network-2-aware config variants for the L2->L2 e2e (task #25)
# from the base fixtures, so they never drift: agglayer-config-l2l2.toml,
# aggkit-l2b-config.toml, bridge-config-l2b.toml. Run before
# `docker compose -f docker-compose.e2e.yml -f docker-compose.l2l2.yml up`.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
F=fixtures

# Rollup #2 aggchain address — deterministic for this snapshot (the aggchain
# proxy is CREATE'd by the RollupManager at a fixed nonce during
# attachAggchainToAL); setup-l2b.sh verifies it at runtime and fails loudly on
# drift. When setup-l2b.sh has already run, prefer its recorded tool output
# (fixtures/l2b/out/sovereign-rollup-out.json, kurtosis sovereign-rollup-out
# format) over the pinned default.
SRO="$F/l2b/out/sovereign-rollup-out.json"
if [ -z "${ROLLUP2_ADDR:-}" ] && [ -s "$SRO" ]; then
  ROLLUP2_ADDR=$(python3 -c "import json;print(json.load(open('$SRO'))['sovereignRollupContract'])")
fi
ROLLUP2_ADDR="${ROLLUP2_ADDR:-0x5D1A491A416feEbf8C123A558ec28A239960bd0E}"
L2B_URL_DOCKER="http://anvil-l2b:8545"
SEQUENCER=0x5b06837A43bdC3dD9F114558DAf4B26ed49842Ed

python3 - "$F" "$ROLLUP2_ADDR" "$L2B_URL_DOCKER" "$SEQUENCER" <<'PY'
import sys
F, ROLLUP2, L2B, SEQ = sys.argv[1:5]
hdr = "# GENERATED by scripts/gen-l2b-configs.sh — edit the base config instead.\n"

# ── agglayer: register network 2 rpc + proof signer ──────────────────────────
s = open(f"{F}/agglayer-config.toml").read()
s = s.replace('[full-node-rpcs]\n1 = "http://miden-agglayer:8546"',
              f'[full-node-rpcs]\n1 = "http://miden-agglayer:8546"\n2 = "{L2B}"')
s = s.replace(f'[proof-signers]\n1 = "{SEQ}"',
              f'[proof-signers]\n1 = "{SEQ}"\n2 = "{SEQ}"')
assert s.count(L2B) == 1 and s.count(f'2 = "{SEQ}"') == 1, "agglayer patch failed"
open(f"{F}/agglayer-config-l2l2.toml","w").write(hdr + s)

# ── aggkit #2: point at L2B + rollup-2 aggchain ──────────────────────────────
s = open(f"{F}/aggkit-config.toml").read()
subs = [
    ('L2URL = "http://miden-agglayer:8546"', f'L2URL = "{L2B}"'),
    ('polygonZkEVMAddress = "0x414e9E227e4b589aF92200508aF5399576530E4e"',
     f'polygonZkEVMAddress = "{ROLLUP2}"'),
    ('URL = "http://miden-agglayer:8546"', f'URL = "{L2B}"'),   # Etherman (L2 sender)
    ('L1ChainID = 2', 'L1ChainID = 31338'),                      # field is the L2 chain id
]
for old, new in subs:
    assert old in s, f"aggkit patch source missing: {old}"
    s = s.replace(old, new)
open(f"{F}/aggkit-l2b-config.toml","w").write(hdr + s)

# ── bridge-service (L2B, ISOLATED): index L1 + L2B ONLY, on its OWN database ──
# Canonical AggKit runs one bridge-service + DB PER rollup. The base
# bridge-service stays Miden-only (bridge-config.toml, unchanged); this variant
# is a SEPARATE service (docker-compose.l2l2.yml: bridge-service-l2b + postgres-l2b)
# that watches L1 + L2B and writes to its own bridge_db on `postgres-l2b`. It is
# just the base config with the L2 pointed at anvil-l2b and the DB host swapped to
# the isolated postgres-l2b. NO AreClaimsBetweenL2sEnabled — canonical kurtosis
# sets it nowhere (claimtxman is L1->L2 only), and on a service that indexes only
# L1+L2B it would be a no-op anyway (no cross-L2 deposits in its DB); the forward
# L2B->Miden and back Miden->L2B claims are both client-submitted with a proof
# fetched from the source rollup's service. The L2B sovereign bridge/GER live at
# the SAME addresses as Miden's (they mirror the same genesis), so the
# single-element bridge/GER/GenBlock lists are already correct.
s = open(f"{F}/bridge-config.toml").read()
subs = [
    ('L2URLs = ["http://miden-agglayer:8546"]', f'L2URLs = ["{L2B}"]'),
    ('Host = "postgres"', 'Host = "postgres-l2b"'),   # both PgStorage blocks -> isolated DB
]
for old, new in subs:
    assert old in s, f"bridge-l2b patch source missing: {old}"
    s = s.replace(old, new)
assert 'postgres-l2b' in s and s.count('postgres-l2b') == 2, "expected exactly 2 DB hosts swapped"
open(f"{F}/bridge-config-l2b.toml","w").write(hdr + s)
print("generated: agglayer-config-l2l2.toml aggkit-l2b-config.toml bridge-config-l2b.toml")
PY

# Normalize generated TOML so `make lint` (taplo fmt --check) stays green — the
# python writer emits valid but un-taplo-formatted TOML.
if command -v taplo >/dev/null 2>&1; then
    RUST_LOG=warn taplo fmt "$F"/agglayer-config-l2l2.toml "$F"/aggkit-l2b-config.toml "$F"/bridge-config-l2b.toml >/dev/null 2>&1 || true
fi
