#!/usr/bin/env bash
# Generate the network-2-aware config variants for the L2->L2 e2e (task #25)
# from the base fixtures, so they never drift: agglayer-config-l2l2.toml,
# aggkit-l2b-config.toml, bridge-config-l2l2.toml. Run before
# `docker compose -f docker-compose.e2e.yml -f docker-compose.l2l2.yml up`.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
F=fixtures

# Rollup #2 aggchain address — deterministic for this snapshot (the aggchain
# proxy is CREATE'd by the RollupManager at a fixed nonce during
# attachAggchainToAL); setup-l2b.sh verifies it at runtime and fails loudly on
# drift. When setup-l2b.sh has already run, prefer its recorded tool output
# (fixtures/l2b/out/sovereign-rollup-out.json, kurtosis sovereign-rollup-out
# format) over the pinned default.
SRO="$F/l2b/out/sovereign-rollup-out.json"
if [ -z "${ROLLUP2_ADDR:-}" ] && [ -s "$SRO" ]; then
  ROLLUP2_ADDR=$(python3 -c "import json;print(json.load(open('$SRO'))['sovereignRollupContract'])")
fi
ROLLUP2_ADDR="${ROLLUP2_ADDR:-0x5D1A491A416feEbf8C123A558ec28A239960bd0E}"
L2B_URL_DOCKER="http://anvil-l2b:8545"
SEQUENCER=0x5b06837A43bdC3dD9F114558DAf4B26ed49842Ed

python3 - "$F" "$ROLLUP2_ADDR" "$L2B_URL_DOCKER" "$SEQUENCER" <<'PY'
import sys
F, ROLLUP2, L2B, SEQ = sys.argv[1:5]
hdr = "# GENERATED by scripts/gen-l2b-configs.sh — edit the base config instead.\n"

# ── agglayer: register network 2 rpc + proof signer ──────────────────────────
s = open(f"{F}/agglayer-config.toml").read()
s = s.replace('[full-node-rpcs]\n1 = "http://miden-agglayer:8546"',
              f'[full-node-rpcs]\n1 = "http://miden-agglayer:8546"\n2 = "{L2B}"')
s = s.replace(f'[proof-signers]\n1 = "{SEQ}"',
              f'[proof-signers]\n1 = "{SEQ}"\n2 = "{SEQ}"')
assert s.count(L2B) == 1 and s.count(f'2 = "{SEQ}"') == 1, "agglayer patch failed"
open(f"{F}/agglayer-config-l2l2.toml","w").write(hdr + s)

# ── aggkit #2: point at L2B + rollup-2 aggchain ──────────────────────────────
s = open(f"{F}/aggkit-config.toml").read()
subs = [
    ('L2URL = "http://miden-agglayer:8546"', f'L2URL = "{L2B}"'),
    ('polygonZkEVMAddress = "0x414e9E227e4b589aF92200508aF5399576530E4e"',
     f'polygonZkEVMAddress = "{ROLLUP2}"'),
    ('URL = "http://miden-agglayer:8546"', f'URL = "{L2B}"'),   # Etherman (L2 sender)
    ('L1ChainID = 2', 'L1ChainID = 31338'),                      # field is the L2 chain id
]
for old, new in subs:
    assert old in s, f"aggkit patch source missing: {old}"
    s = s.replace(old, new)
open(f"{F}/aggkit-l2b-config.toml","w").write(hdr + s)

# ── bridge-service: append network 2 to the multi-network lists ──────────────
s = open(f"{F}/bridge-config.toml").read()
subs = [
    ('L2URLs = ["http://miden-agglayer:8546"]',
     f'L2URLs = ["http://miden-agglayer:8546", "{L2B}"]'),
    ('L2GenBlockNumbers = [0]', 'L2GenBlockNumbers = [0, 0]'),
    ('L2PolygonBridgeAddresses = ["0xC8cbEBf950B9Df44d987c8619f092beA980fF038"]',
     'L2PolygonBridgeAddresses = ["0xC8cbEBf950B9Df44d987c8619f092beA980fF038", "0xC8cbEBf950B9Df44d987c8619f092beA980fF038"]'),
    ('RequireSovereignChainSmcs = [true]', 'RequireSovereignChainSmcs = [true, true]'),
    ('L2PolygonZkEVMGlobalExitRootAddresses = [\n  "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa",\n]',
     'L2PolygonZkEVMGlobalExitRootAddresses = [\n  "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa",\n  "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa",\n]'),
]
for old, new in subs:
    assert old in s, f"bridge patch source missing: {old}"
    s = s.replace(old, new)
open(f"{F}/bridge-config-l2l2.toml","w").write(hdr + s)
print("generated: agglayer-config-l2l2.toml aggkit-l2b-config.toml bridge-config-l2l2.toml")
PY
