on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CARGO_PROFILE: release
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - run: make install-tools
      - run: make lint
      - run: make build
      - run: make test-unit
      - run: make test-scripts
